name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"] # 建议先固定一个版本进行测试

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          # uv 官方推荐的安装方式
          curl -LsSf https://astral.sh/uv/install.sh | sh
          source ~/.cargo/env
          uv --version

      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-${{ matrix.python-version }}-uv-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-uv-

      - name: Install dependencies with uv
        run: |
          uv pip install -e ".[dev]"

      - name: Lint with ruff
        run: |
          ruff format --check .
          ruff check .

      - name: Test with pytest
        run: |
          pytest --cov=src
